using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace UserInterfaceGenerator;

[Generator]
public class ElementsGenerator : IIncrementalGenerator
{
    private static readonly Regex UxmlElementRegex = new("""
                                                         <(?:ui:)?([\w:\.]+).*?name="_([\w-]+)"
                                                         """, RegexOptions.Compiled);
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var uxmlFilesProvider = context.AdditionalTextsProvider
            .Where(file => Path.GetExtension(file.Path) == ".additionalfile" || Path.GetExtension(file.Path) == ".uxml" )
            .Collect();

        var assemblyNameProvider = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName);

        var combinedProvider = assemblyNameProvider.Combine(uxmlFilesProvider);

        context.RegisterSourceOutput(combinedProvider, (productionContext, source) =>
        {
            var (assemblyName, uxmlFiles) = source;

            if (assemblyName != "Assembly-CSharp" && assemblyName != "UserInterfaceGenerator.Sample") 
                return;
            
            foreach (var file in uxmlFiles)
            {
                var uxmlText = file.GetText();
                if (uxmlText == null) 
                    continue;
                
                var fileName = Path.GetFileNameWithoutExtension(file.Path).Replace(".UserInterfaceGenerator", "") + "Elements" ;
                
                if (!ElementsGeneratorLogic(uxmlText, fileName, out var sourceStream)) 
                    continue;
                
                productionContext.AddSource($"{fileName}.g.cs", SourceText.From(sourceStream, Encoding.UTF8, canBeEmbedded: true));
            }
        });
    }

    private static bool ElementsGeneratorLogic(SourceText uxmlText, string fileName, out MemoryStream sourceStream)
    {
        sourceStream = new MemoryStream();
        StreamWriter sourceStreamWriter = new(sourceStream, Encoding.UTF8, bufferSize: 1024, leaveOpen: true);
        IndentedTextWriter codeWriter = new(sourceStreamWriter);
        
        codeWriter.WriteLine("// <auto-generated>");
        codeWriter.WriteLine("using System;");
        codeWriter.WriteLine("using UnityEngine;");
        codeWriter.WriteLine("using UnityEngine.UIElements;");
        codeWriter.WriteLine();
        codeWriter.WriteLine("namespace UserInterfaceGenerator");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;

        codeWriter.WriteLine($"public class {fileName}");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;

        var typesAndNames = new List<(string elementType, string elementName)>();

        // Elements
        foreach (var line in uxmlText.Lines)
        {
            var lineText = line.ToString().Trim();

            var match = UxmlElementRegex.Match(lineText);
            if (!match.Success) 
                continue;
            
            var elementType = match.Groups[1].Value;
            var elementName = match.Groups[2].Value;

            typesAndNames.Add((elementType, elementName));
            
            codeWriter.WriteLine($"public {elementType} {elementName} {{ get; private set; }}");
            codeWriter.WriteLine();
        }
        
        if (typesAndNames.Count == 0)
        {
            sourceStreamWriter.Dispose();
            return false;
        }
        
        // Constructor
        codeWriter.WriteLine($"public {fileName}(VisualElement rootElement, VisualTreeAsset visualTreeAssetSource)");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;
        
        codeWriter.WriteLine("var contentHash = visualTreeAssetSource.contentHash;");
        codeWriter.WriteLine("");
        
        foreach (var typeAndName in typesAndNames)
        {
            codeWriter.WriteLine($"{typeAndName.elementName} = rootElement.Query<{typeAndName.elementType}>(\"_{typeAndName.elementName}\").Where(element => element.visualTreeAssetSource.contentHash == contentHash).First();");
        }
        
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        // Closing brackets
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        codeWriter.Flush();
        sourceStreamWriter.Flush();
        
        sourceStream.Position = 0;
        return true;
    }
}