using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace UserInterfaceGenerator;

[Generator]
public class ElementsGenerator : IIncrementalGenerator
{
    private static readonly Regex UxmlElementRegex = new("""
                                                         <(?:uie?:)?(?!AttributeOverrides\b)([\w:\.]+)(?:.*?template="([^"]+)")?.*?name="_([\w-]+)"
                                                         """, RegexOptions.Compiled);

    private const string RuntimeAssembly = "UserInterfaceGenerator.Runtime";
    private const string EditorAssembly = "UserInterfaceGenerator.Editor";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var uxmlFilesProvider = context.AdditionalTextsProvider
            .Where(file => Path.GetExtension(file.Path) == ".additionalfile")
            .Collect();

        var assemblyNameProvider = context.CompilationProvider
            .Select((compilation, _) => compilation.AssemblyName);

        var combinedProvider = assemblyNameProvider.Combine(uxmlFilesProvider);

        context.RegisterSourceOutput(combinedProvider, (productionContext, source) =>
        {
            var (assemblyName, uxmlFiles) = source;

            if (assemblyName != RuntimeAssembly && assemblyName != EditorAssembly) 
                return;
            
            foreach (var file in uxmlFiles)
            {
                var uxmlText = file.GetText();
                if (uxmlText == null) 
                    continue;
                
                var isEditorUxml = uxmlText.ToString().Contains("editor-extension-mode=\"True\"");
                if (isEditorUxml && assemblyName == RuntimeAssembly)
                    continue;
                
                if (!isEditorUxml && assemblyName == EditorAssembly)
                    continue;
                
                var fileName = Path.GetFileNameWithoutExtension(file.Path).Replace(".UserInterfaceGenerator", "") + "Elements";

                ElementsGeneratorLogic(uxmlText, fileName, isEditorUxml, out var sourceStream);
                productionContext.AddSource($"{fileName}.g.cs", SourceText.From(sourceStream, Encoding.UTF8, canBeEmbedded: true));
            }
        });
    }

    private void ElementsGeneratorLogic(SourceText uxmlText, string fileName, bool isEditorUxml, out MemoryStream sourceStream)
    {
        sourceStream = new MemoryStream();
        StreamWriter sourceStreamWriter = new(sourceStream, Encoding.UTF8, bufferSize: 1024, leaveOpen: true);
        IndentedTextWriter codeWriter = new(sourceStreamWriter);
        
        codeWriter.WriteLine("// <auto-generated>");
        codeWriter.WriteLine("using System;");
        codeWriter.WriteLine("using UnityEngine;");
        codeWriter.WriteLine("using UnityEngine.UIElements;");
        codeWriter.WriteLine("#if UNITY_EDITOR");
        codeWriter.WriteLine("using UnityEditor.UIElements;");
        codeWriter.WriteLine("#endif");
        codeWriter.WriteLine();
        if (isEditorUxml)
        {
            codeWriter.WriteLine("namespace UserInterfaceGenerator.Editor");
        }
        else
        {
            codeWriter.WriteLine("namespace UserInterfaceGenerator.Runtime");
        }
        codeWriter.WriteLine("{");
        codeWriter.Indent++;

        codeWriter.WriteLine($"public class {fileName}");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;
        
        // Elements
        var typesAndNames = new List<(string elementTypeTemplate, string elementType, string elementName)>();
        foreach (var line in uxmlText.Lines)
        {
            var lineText = line.ToString().Trim();

            var match = UxmlElementRegex.Match(lineText);
            if (!match.Success) 
                continue;
            
            var elementTypeTemplate = match.Groups[2].Value == string.Empty ? string.Empty : match.Groups[2].Value + "Elements";
            var elementType = match.Groups[1].Value;
            var elementName = match.Groups[3].Value;

            typesAndNames.Add((elementTypeTemplate, elementType, elementName));

            if (elementTypeTemplate == string.Empty)
            {
                codeWriter.WriteLine($"public {elementType} {elementName} {{ get; private set; }}");
            }
            else
            {
                codeWriter.WriteLine($"public {elementTypeTemplate} {elementName} {{ get; private set; }}");
            }
            
            codeWriter.WriteLine();
        }
        
        // Constructor
        codeWriter.WriteLine($"public {fileName}(VisualElement rootElement, VisualTreeAsset visualTreeAssetSource)");
        codeWriter.WriteLine("{");
        codeWriter.Indent++;
        
        codeWriter.WriteLine("var contentHash = visualTreeAssetSource.contentHash;");
        codeWriter.WriteLine("");

        var i = 0;
        foreach (var typeAndName in typesAndNames)
        {
            if (typeAndName.elementTypeTemplate == string.Empty)
            {
                codeWriter.WriteLine($"{typeAndName.elementName} = rootElement.Query<{typeAndName.elementType}>(\"_{typeAndName.elementName}\").Where(element => element.visualTreeAssetSource.contentHash == contentHash).First();");
            }
            else
            {
                codeWriter.WriteLine($"var rootElement{typeAndName.elementName} = rootElement.Query<TemplateContainer>(\"_{typeAndName.elementName}\").Where(element => element.visualTreeAssetSource.contentHash == contentHash).First();");
                codeWriter.WriteLine($"{typeAndName.elementName} = new(rootElement{typeAndName.elementName}, rootElement{typeAndName.elementName}.templateSource);");
            }
            
            if (i < typesAndNames.Count - 1)
                codeWriter.WriteLine("");
            
            i++;
        }
        
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        // Closing brackets
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        codeWriter.Indent--;
        codeWriter.WriteLine("}");
        
        codeWriter.Flush();
        sourceStreamWriter.Flush();
        
        sourceStream.Position = 0;
    }
}